<a href="https://colab.research.google.com/github/EsaraHossain/Assignment/blob/main/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [ ]:
import numpy as np
array = np.random.randint(1, 101, size=(3, 3))
print("Original array:")
print(array)
transposed_array = np.transpose(array)
print("\nTransposed array:")
print(transposed_array)


Original array:
[[22 99 98]
 [80 90 53]
 [46 55 10]]

Transposed array:
[[22 80 46]
 [99 90 55]
 [98 53 10]]


In [ ]:
#Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [ ]:
import numpy as np

array_1d = np.arange(10)

print("Original 1D array:")
print(array_1d)

array_2x5 = array_1d.reshape((2, 5))

print("\nReshaped 2x5 array:")
print(array_2x5)

array_5x2 = array_2x5.reshape((5, 2))

print("\nReshaped 5x2 array:")
print(array_5x2)


Original 1D array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped 2x5 array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped 5x2 array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
#Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [ ]:
array_4x4 = np.random.rand(4, 4)
print("Original 4x4 array:")
print(array_4x4)
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 array with border of zeros:")
print(array_6x6)


Original 4x4 array:
[[0.67201547 0.87432887 0.32323732 0.58726595]
 [0.42942875 0.65917107 0.60128755 0.93099216]
 [0.8114343  0.77266741 0.05306558 0.73075396]
 [0.99665304 0.33085336 0.82345686 0.49075963]]

6x6 array with border of zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.67201547 0.87432887 0.32323732 0.58726595 0.        ]
 [0.         0.42942875 0.65917107 0.60128755 0.93099216 0.        ]
 [0.         0.8114343  0.77266741 0.05306558 0.73075396 0.        ]
 [0.         0.99665304 0.33085336 0.82345686 0.49075963 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [ ]:
# Using NumPy, create an array of integers from 10 to 60 with a step of 5.
array = np.arange(10, 61, 5)
print(array)

[10 15 20 25 30 35 40 45 50 55 60]


In [ ]:
#Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [ ]:
string_array = np.array(['python', 'numpy', 'pandas'])
uppercase_array = np.char.upper(string_array)
lowercase_array = np.char.lower(string_array)
titlecase_array = np.char.title(string_array)
capitalize_array = np.char.capitalize(string_array)

print("Original array:")
print(string_array)

print("\nUppercase array:")
print(uppercase_array)

print("\nLowercase array:")
print(lowercase_array)

print("\nTitlecase array:")
print(titlecase_array)

print("\nCapitalized array:")
print(capitalize_array)


Original array:
['python' 'numpy' 'pandas']

Uppercase array:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase array:
['python' 'numpy' 'pandas']

Titlecase array:
['Python' 'Numpy' 'Pandas']

Capitalized array:
['Python' 'Numpy' 'Pandas']


In [ ]:
# Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [ ]:

words_array = np.array(['python', 'numpy', 'pandas'])
spaced_words_array = np.char.join(' ', words_array)
print("Original array:")
print(words_array)
print("\nArray with spaces between characters:")
print(spaced_words_array)


Original array:
['python' 'numpy' 'pandas']

Array with spaces between characters:
['p y t h o n' 'n u m p y' 'p a n d a s']


In [ ]:
# Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [ ]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
addition_result = array1 + array2
subtraction_result = array1 - array2
multiplication_result = array1 * array2
division_result = array1 / array2
print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nElement-wise addition:")
print(addition_result)
print("\nElement-wise subtraction:")
print(subtraction_result)
print("\nElement-wise multiplication:")
print(multiplication_result)
print("\nElement-wise division:")
print(division_result)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [ ]:
#Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [ ]:
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)
diagonal_elements = np.diag(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


In [ ]:
# Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [ ]:
import numpy as np
def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True
array = np.random.randint(0, 1001, size=100)
prime_numbers = np.array([num for num in array if is_prime(num)])
print("Array of random integers:")
print(array)
print("\nPrime numbers in the array:")
print(prime_numbers)


Array of random integers:
[874 358 434 385 909  55 758 764 365 393 403 127 720 944  47 652  55  89
 970 752 171  86  47 501 134 522 972 791  60  87 873   8 705 513 420 950
 116 172 414 292 999  87 243 215 404 857 734 287 846 471 358 427 992 532
 379 593 424 587 520 353 435 908 253 292 206 867 385 368 541 418 827 741
 889 843 966 288 885 253 590 710 557 309  10 400  33 734 990 354  40 524
 588  31 764 700 289 436 194 818 665 941]

Prime numbers in the array:
[127  47  89  47 857 379 593 587 353 541 827 557  31 941]


In [ ]:
#Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [ ]:
import numpy as np

daily_temperatures = np.random.uniform(low=0, high=35, size=30)
weekly_averages = np.mean(daily_temperatures.reshape(3, 10), axis=1)
print("Daily temperatures for the month:")
print(daily_temperatures)

print("\nWeekly averages:")
print(weekly_averages)


Daily temperatures for the month:
[ 5.56393543  3.86312994 22.97153563  4.8364033   6.88038266 12.90538097
 28.73476304  3.39854465 29.32807176  3.36344428 34.17608128 16.40279206
 34.18663809 21.16959319 25.87422528  1.37157273  9.89824369  4.20687964
 10.36490691  4.15547016 11.12941128 14.49920481  2.24516237 24.23652418
 19.8310509   9.28863218 18.31368187  3.28791788 20.15812734 32.52536692]

Weekly averages:
[12.18455917 16.1806403  15.55150797]
